# Copyright (c) 2024 Realtek Semiconductor Corp.
# SPDX-License-Identifier: Apache-2.0

# The west manifest file for Realtek Nuwa SDK.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: git@github.com:Ameba-AIoT

  # workspace topdir cannot be a .git repository, otherwise west build will fail, which means .west and .git can't be in the same directory.
  # If two projects have the same name, the project defined first has highest precedence.
  # Please add items below based on alphabetical order
  projects:
    - name: hal_realtek
      repo-path: nuwa_hal_realtek
      path: modules/hal/realtek
      revision: f606d1959b29473caccd9f7a3bb753095a9d9240
    - name: tools
      # repo-path is optional. If given, this is concatenated on to the remote’s url-base instead of the project’s name to form its fetch URL.
      repo-path: nuwa_tools
      path: tools
      revision: 7f5ec8eada94560cc9dfb0241683c35f2581194b
    # - name: cmsis
    #   path: modules/hal/cmsis
    #   revision: main
    - name: zephyr
      path: zephyr
      # west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis
      revision: 73d37c6b6a917bd4f1bdf2d7d448b5a458bb491d

# The available self keys are path/west-commands/import, and all items are optional.
# If path is not given, the basename of the path component in the manifest repository URL(by west init -m) will be used by default.
# the .git repository containing west.yml is never modified by west
# the cmsis/realtek/zephyr need to be a .git by west and cmake.
  self:
    path: manifests
