# Copyright (c) 2024 Realtek Semiconductor Corp.
# SPDX-License-Identifier: Apache-2.0

# The west manifest file for Realtek Nuwa SDK.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/Ameba-AIoT
      # url-base: git@github.com:Ameba-AIoT

  # workspace topdir cannot be a .git repository, otherwise west build will fail, which means .west and .git can't be in the same directory.
  # If two projects have the same name, the project defined first has highest precedence.
  # Please add items below based on alphabetical order
  projects:
    - name: hal_realtek
      repo-path: nuwa_hal_realtek
      path: modules/hal/realtek
      revision: 6d731dd9aff74e58d2bd5fde67a148f840f514e6
      west-commands: west/west-commands.yml
    - name: nuwa_lib
      path: modules/hal/realtek/zephyr/blobs/ameba
      revision: 924d7ae2d185eead702a726abe42d1bed1bbf308
    - name: nuwa-mcuboot
      path: bootloader/mcuboot
      revision: 029c1a882bb9063cd70bb0a676de0d4740d12d9f
    - name: tf-m
      path: modules/tee/tf-m/trusted-firmware-m
      repo-path: nuwa-trusted-firmware-m
      revision: db290141044eaa97a380512e5c9fc400f2b581d0
    - name: lvgl
      path: modules/lib/gui/lvgl
      repo-path: lvgl-zephyr
      revision: 4bf24d50859c45415813deece82d97b192820466
    - name: nuwa_tools
      path: tools
      revision: 6c1fc863dd76420870bdfdfb984c2d4cd3bed0cd
    - name: zephyr
      path: zephyr
      # west-commands: scripts/west-commands.yml
      revision: 3be1be06b3fa34ae684cb5174287889383cef35e
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - littlefs
          - fatfs
          - mbedtls
          - mbedtls-3.6
          - zcbor
          - tf-m-tests
          - tf-psa-crypto

# The available self keys are path/west-commands/import, and all items are optional.
# If path is not given, the basename of the path component in the manifest repository URL(by west init -m) will be used by default.
# the .git repository containing west.yml is never modified by west
# the cmsis/realtek/zephyr need to be a .git by west and cmake.
  self:
    path: manifests
