# Copyright (c) 2024 Realtek Semiconductor Corp.
# SPDX-License-Identifier: Apache-2.0

# The west manifest file for Realtek Nuwa SDK.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/Ameba-AIoT
      # url-base: git@github.com:Ameba-AIoT

  # workspace topdir cannot be a .git repository, otherwise west build will fail, which means .west and .git can't be in the same directory.
  # If two projects have the same name, the project defined first has highest precedence.
  # Please add items below based on alphabetical order
  projects:
    - name: hal_realtek
      repo-path: nuwa_hal_realtek
      path: modules/hal/realtek
      revision: 0bf0c655e817ca6cf1d0aa24c1007ee631bcf984
    - name: nuwa_lib
      path: modules/hal/realtek/zephyr/blobs/ameba
      revision: 83e8ff741cd69db666d62e5cb287b0912a553ca7
    - name: lvgl
      path: modules/lib/gui/lvgl
      repo-path: lvgl-zephyr
      revision: ameba/v4.2.1
    - name: tools
      # repo-path is optional. If given, this is concatenated on to the remote’s url-base instead of the project’s name to form its fetch URL.
      repo-path: nuwa_tools
      path: tools
      revision: 76c9299d5ce9c1f851c6e4bca9deaa601cf4b4f0
    - name: zephyr
      path: zephyr
      # west-commands: scripts/west-commands.yml
      revision: 7cbc7466178f94d0f65adc0ce5f6165748a7976c
      import:
        name-allowlist:
          - cmsis_6
          - littlefs
          - fatfs
          - mbedtls
          - zcbor

# The available self keys are path/west-commands/import, and all items are optional.
# If path is not given, the basename of the path component in the manifest repository URL(by west init -m) will be used by default.
# the .git repository containing west.yml is never modified by west
# the cmsis/realtek/zephyr need to be a .git by west and cmake.
  self:
    path: manifests
