# Copyright (c) 2024 Realtek Semiconductor Corp.
# SPDX-License-Identifier: Apache-2.0

# The west manifest file for Realtek Nuwa SDK.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/Ameba-AIoT
      # url-base: git@github.com:Ameba-AIoT

  # workspace topdir cannot be a .git repository, otherwise west build will fail, which means .west and .git can't be in the same directory.
  # If two projects have the same name, the project defined first has highest precedence.
  # Please add items below based on alphabetical order
  projects:
    - name: hal_realtek
      repo-path: nuwa_hal_realtek
      path: modules/hal/realtek
      revision: cc622690ac43402f48c6254f65cb1d1aa3a54ee2
    - name: nuwa_lib
      path: modules/hal/realtek/zephyr/blobs/ameba
      revision: 144be47089f33b26839d6fb00bf8b273bf2d8891
    - name: nuwa-mcuboot
      path: bootloader/mcuboot
      revision: cefe2c6178e68370e713a8230158004bf94eefdf
    - name: tf-m
      path: modules/tee/tf-m/trusted-firmware-m
      repo-path: nuwa-trusted-firmware-m
      revision: 0be61d2a7ebfbfc0be532f26706b665267e16fc5
    - name: lvgl
      path: modules/lib/gui/lvgl
      repo-path: lvgl-zephyr
      revision: ameba/v4.2.1
    - name: nuwa_tools
      path: tools
      revision: d0554ee42023f8139ffd032e110ee2b69dc01602
    - name: zephyr
      path: zephyr
      # west-commands: scripts/west-commands.yml
      revision: 6441bbdce9856232b1850a56b6c3d5df228d4c98
      import:
        name-allowlist:
          - cmsis_6
          - littlefs
          - fatfs
          - mbedtls
          - zcbor

# The available self keys are path/west-commands/import, and all items are optional.
# If path is not given, the basename of the path component in the manifest repository URL(by west init -m) will be used by default.
# the .git repository containing west.yml is never modified by west
# the cmsis/realtek/zephyr need to be a .git by west and cmake.
  self:
    path: manifests
